add_newline = false
format = """$directory$git_branch$git_metrics$character"""
right_format = """$all"""

[character]
# Make character more subtle for success to only pop out in case of failure.
success_symbol = '[❯](bold grey)'

[aws]
symbol = ' '
format = '[$symbol($profile )(\($region\) )(\[$duration\] )]($style)'

[kubernetes]
disabled = false
symbol = ' '
style = 'blue bold'
format = '[$symbol$context]($style) '
contexts = [
  # In case of EKS, remove all of the ARN except for the cluster name.
  { context_alias = '$cluster', context_pattern = '.*\/+(?P<cluster>.+)' }
]

[docker_context]
disabled = true

[python]
disabled = true
symbol = ' '

[lua]
disabled = true

[git_branch]
style = 'bold grey'
format = '[$symbol$branch(:$remote_branch)]($style) '

[git_status]
disabled = true

[git_metrics]
disabled = false
added_style = 'green'
deleted_style = 'red'
format = '[󰐖 $added]($added_style) [󰍵 $deleted]($deleted_style) '

[cmd_duration]
min_time = 1_000
