add_newline = false
format = """$directory$git_branch$git_status$character"""
right_format = """$all"""

[aws]
symbol = ' '
format = '[$symbol($profile )(\($region\) )(\[$duration\] )]($style)'

[kubernetes]
disabled = false
symbol = ' '
style = 'blue bold'
format = '[$symbol$context]($style) '

[python]
symbol = ' '

[lua]
disabled = true

[git_branch]
style = 'bold grey'
format = '[$symbol$branch(:$remote_branch)]($style) '

[cmd_duration]
disabled = true
